[project]
name = "3ftx-novel-taxa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "distinctipy>=1.3.4",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.3",
    "pandas>=2.2.3",
    "plotly>=6.0.1",
    "protspace[frontend]>=3.1.1",
    "pyfaidx>=0.9.0.3",
    "pyfamsa>=0.6.1",
    "requests>=2.32.0",
    "taxopy>=0.14.0",
    "tqdm>=4.67.1",
]
